# https://docs.microsoft.com/de-de/azure/devops/pipelines/agents/hosted?view=azure-devops#software
trigger:
- master

variables:
  python-version: "3.7"
  create-mingw-profile: |
    (
      echo [settings]
      echo os=Windows
      echo os_build=Windows
      echo arch=x86_64
      echo arch_build=x86_64
      echo compiler=gcc
      echo compiler.version=8
      echo compiler.exception=seh
      echo compiler.libcxx=libstdc++11
      echo compiler.threads=posix
      echo build_type=Release
      echo [build_requires]
      echo mingw_installer/1.0@conan/stable
      echo msys2/20190524
    ) > mingw

stages:
- stage: create
  displayName: create conan package
  jobs:
  - job: CreatePackage
    strategy:
      matrix:
        linuxubuntu:
          imageName: ubuntu-latest
          prepare-env: |
            export PATH="$PATH:/home/vsts/.local/bin"
            sudo apt install -y python3-setuptools
          pip-command: pip3
          conan-profile: ""
#        linuxdocker:
#          imageName: ubuntu-latest
        macos:
          imageName: macOS-latest
          prepare-env: export PATH=$PATH:$HOME/.local/bin
          pip-command: pip
          conan-profile: ""
        windows:
          imageName: windows-latest
          prepare-env: $(create-mingw-profile)
          pip-command: python -m pip
          conan-profile: "-p mingw"

    pool:
      vmImage: $(imageName)
    steps:
      - task: UsePythonVersion@0
        inputs:
         versionSpec: $(python-version)
      - script: |
         $(prepare-env)
         $(pip-command) install --user --upgrade pip
         $(pip-command) install --user conan
         conan user
         conan create . -s compiler.libcxx=libstdc++11 $(conan-profile)
        displayName: create conan package

  - job: CreatePackageOtherLinux
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo "Hello CI"
        displayName: whatever


- stage: publish
  displayName: publish conan package
  dependsOn: create
  jobs:
    - job: PublishPackage
      pool:
        vmImage: ubuntu-latest
      steps:
        - script: |
            echo "Hello CI"
          displayName: whatever
