include conanbuildinfo.mak

RACK_DIR ?= $(CONAN_ROOT_VCVRACK-SDK-INSTALLER)
RACK_USER_DIR ?= testuserdir


SOURCES += $(wildcard *.cpp)

# Include the Rack plugin Makefile framework
include $(RACK_DIR)/plugin.mk
